"""Canonicalize ICS-NAD `state` labels across all 61 Labeled_CSV files.

The published dataset's per-file labeling scripts (see external/Code-for-ICS-NAD-Dataset/
labeling_tcx.py, labeling_ws.py) are hardcoded, copy-pasted per capture file and were not
always updated correctly. Confirmed issues found by direct inspection (see data-quality
report generated by this module for the full, authoritative list):

  - Wrong attack-type string but correct BENIGN/attack row split (e.g. ABB_LONG_synflood_faster
    is entirely labeled ACKFLOOD instead of SYNFLOOD).
  - Generic placeholder label 'TCP' instead of the real attack type (4 Schneider files).
  - Attack traffic entirely mislabeled BENIGN (e.g. Siemens_LONG_synflood_fast, ~4.6M rows).
  - No `state` column at all (5 files).

Strategy: the filename's attack-type token is the primary ground truth (it's what the
dataset authors intended to capture), corroborated by validated protocol-level signatures
(TCP flag rates, fragment rate, source==dest address) that were checked against known-clean
reference files before use. Every row whose final label required overriding or reconstructing
the original `state` value is flagged `label_uncertain=True` for downstream transparency.
"""

import re
from pathlib import Path

import polars as pl

from icsnad_gym.schema import read_csv_typed

CANONICAL_LABELS = {
    "BENIGN", "ACKFLOOD", "SYNFLOOD", "TCPFLOOD", "ICMPFLOOD", "SMURF", "FRAGGLE",
    "PINGOFDEATH", "TEARDROP", "LAND", "WINNUKE", "TCPFIN1", "TCPALL", "TCPSYNFIN",
    "PORTSCAN", "NMAP", "ROUTEIP", "ICMPBIG", "ICMPNOTREACH", "ICMPREDIRECT", "ARP",
}

# Ordered filename-token -> canonical-label regex dispatch. Order matters: more specific
# patterns (tcpsynfin0) must be checked before more general ones would falsely match.
_TOKEN_MAP = [
    (r"tcpsynfin0?", "TCPSYNFIN"),
    (r"tcpfin1", "TCPFIN1"),
    (r"tcpall0?", "TCPALL"),
    (r"synflood", "SYNFLOOD"),
    (r"ackflood", "ACKFLOOD"),
    (r"tcpflood", "TCPFLOOD"),
    (r"icmpflood", "ICMPFLOOD"),
    (r"icmpbig", "ICMPBIG"),
    (r"icmpnotreach", "ICMPNOTREACH"),
    (r"icmpredirect", "ICMPREDIRECT"),
    (r"pingofdeath", "PINGOFDEATH"),
    (r"smurf", "SMURF"),
    (r"fraggle", "FRAGGLE"),
    (r"teardrop", "TEARDROP"),
    (r"land", "LAND"),
    (r"winnuke", "WINNUKE"),
    (r"portscan", "PORTSCAN"),
    (r"nmap", "NMAP"),
    (r"routeip", "ROUTEIP"),
    (r"arp", "ARP"),
    (r"udpflood", "UDPFLOOD"),  # excluded from CANONICAL_LABELS: no matching CSV exists
]

# Simple case/typo normalization applied to any non-BENIGN state value before comparison
# against the filename-derived expected label.
_TYPO_FIXES = {
    "ACKPFLOOD": "ACKFLOOD",
    "WINNUKE": "WINNUKE", "WinNuke": "WINNUKE",
    "FRAGGLE": "FRAGGLE", "Fraggle": "FRAGGLE",
    "SMURF": "SMURF", "Smurf": "SMURF",
    "TCPSYNFIN0": "TCPSYNFIN", "TCPSYNFIN": "TCPSYNFIN",
    "ICMPNOTREATH": "ICMPNOTREACH", "ICMPNOTREACH": "ICMPNOTREACH",
    "SYN": "SYNFLOOD",  # Schneider's shorthand for the synflood attack, confirmed 1:1 by file
}


def expected_label_from_filename(filename: str) -> str | None:
    low = filename.lower()
    for pattern, label in _TOKEN_MAP:
        if re.search(pattern, low):
            return label
    return None


def normalize_state(raw: str) -> str:
    if raw is None:
        return "BENIGN"
    up = raw.strip()
    if up.upper() == "BENIGN":
        return "BENIGN"
    return _TYPO_FIXES.get(up, up.upper())


# Per-file explicit reconstruction strategy for the 18 files confirmed broken/incomplete.
# method: "rename"      -> keep existing BENIGN/non-BENIGN row split, override the
#                           non-BENIGN label string to the filename-derived canonical type.
#         "signature"    -> row-level BENIGN/attack split is not trustworthy (or absent);
#                           re-derive it from a validated protocol-level feature signature.
#         "exclude"      -> too small / signature doesn't transfer reliably; drop non-BENIGN
#                           reconstruction attempt, keep rows as-is, flag file in report.
FILE_STRATEGY: dict[str, dict] = {
    # --- rename: BENIGN/attack split is correct, only the attack-type string is wrong ---
    "ABB_LONG_synflood_faster_1_01-.csv": {"method": "rename"},
    "ABB_teardrop_fast_0715.csv": {"method": "rename"},
    "Schneider_tcpall0_0710.csv": {"method": "rename"},
    "Schneider_tcpfin1_0710.csv": {"method": "rename"},
    "Schneider_tcpflood_fast_0710.csv": {"method": "rename"},
    "Schneider_tcpsynfin0_0710.csv": {"method": "rename"},
    "ABB_LONG_tcpflood_faster_1_01-.csv": {"method": "rename"},  # mixed ACKFLOOD+TCPFLOOD -> all TCPFLOOD

    # --- signature: row-level split must be reconstructed from flow features ---
    "ABB_land_faster_0715_part1.csv": {"method": "signature", "sig": "same_addr"},
    "Siemens_tcpfin1_0709.csv": {"method": "signature", "sig": "tcpfin1_flags"},
    "Siemens_tcpsynfin0_0709.csv": {"method": "signature", "sig": "tcpsynfin_flags"},
    "Siemens_tcpall0_0709.csv": {"method": "signature", "sig": "tcpall_flags"},
    "Siemens_teardrop_0709.csv": {"method": "signature", "sig": "fragment_rate"},
    "Siemens_LONG_synflood_fast_1_01-.csv": {"method": "signature", "sig": "synflood_flags"},
    "Siemens_LONG_tcpflood_fast_1_01(1).csv": {"method": "signature", "sig": "tcpflood_flags"},
    "Schneider_tcpflood_faster_0723_part1_.csv": {"method": "signature", "sig": "tcpflood_flags"},

    # --- exclude: tiny file (374 rows), NMAP addressing scheme doesn't transfer across brands ---
    "Schneider_nmap_0710-.csv": {"method": "exclude"},
}


def _apply_signature(df: pl.DataFrame, sig: str, expected_label: str) -> pl.Series:
    """Return a boolean Series: True where the row matches the attack signature."""
    if sig == "same_addr":
        return df["sAddress"] == df["rAddress"]
    if sig == "fragment_rate":
        return (df["sFragmentRate"].fill_null(0) > 0) | (df["rFragmentRate"].fill_null(0) > 0)
    if sig == "tcpfin1_flags":
        return (
            (df["protocol"] == "IPV4-TCP")
            & (df["sFinRate"].fill_null(0) == 1.0)
            & (df["sSynRate"].fill_null(0) == 0.0)
        )
    if sig == "tcpsynfin_flags":
        return (
            (df["protocol"] == "IPV4-TCP")
            & (df["sFinRate"].fill_null(0) == 1.0)
            & (df["sSynRate"].fill_null(0) == 1.0)
        )
    if sig == "tcpall_flags":
        return (
            (df["protocol"] == "IPV4-TCP")
            & (df["sFinRate"].fill_null(0) == 0.0)
            & (df["sSynRate"].fill_null(0) == 0.0)
            & (df["sAckRate"].fill_null(1) == 0.0)
        )
    if sig == "synflood_flags":
        return (
            (df["protocol"] == "IPV4-TCP")
            & (df["sSynRate"].fill_null(0) >= 0.9)
            & (df["sAckRate"].fill_null(1) <= 0.1)
        )
    if sig == "tcpflood_flags":
        # Volumetric TCP flood: TCP protocol with a dominant, non-handshake flag rate
        # profile distinguishable from ordinary BENIGN ICS polling traffic (validated
        # against the TCPFLOOD-labeled subset of ABB_LONG_tcpflood_faster).
        return (df["protocol"] == "IPV4-TCP") & (df["sAckRate"].fill_null(1) < 0.5)
    raise ValueError(f"unknown signature {sig!r}")


def harmonize_file(path: Path) -> tuple[pl.DataFrame, dict]:
    """Load one CSV, return (harmonized DataFrame, per-file report dict).

    Harmonized DataFrame has canonical `state` values and a boolean `label_uncertain` column.
    """
    fname = path.name
    expected = expected_label_from_filename(fname)
    strategy = FILE_STRATEGY.get(fname, {"method": "trust"})
    header = pl.read_csv(path, n_rows=0).columns
    has_state = "state" in header

    report = {
        "file": fname, "expected_label": expected, "method": strategy["method"],
        "had_state_column": has_state,
    }

    if strategy["method"] == "exclude":
        df = read_csv_typed(path)
        if not has_state:
            df = df.with_columns(pl.lit("BENIGN").alias("state"))
        df = df.with_columns(pl.lit(False).alias("label_uncertain"))
        report["note"] = "excluded from reconstruction (too small / signature unreliable)"
        report["n_rows"] = len(df)
        return df, report

    if strategy["method"] == "signature" or not has_state:
        sig = strategy.get("sig")
        df = read_csv_typed(path)
        if sig is None:
            raise ValueError(f"{fname}: no state column and no signature strategy defined")
        is_attack = _apply_signature(df, sig, expected)
        df = df.with_columns(
            pl.when(is_attack).then(pl.lit(expected)).otherwise(pl.lit("BENIGN")).alias("state"),
            pl.lit(True).alias("label_uncertain"),  # reconstructed, always flagged
        )
        report["n_rows"] = len(df)
        report["n_attack_rows"] = int(is_attack.sum())
        return df, report

    # method == "trust" or "rename": state column exists and BENIGN/attack split is trustworthy
    df = read_csv_typed(path)
    report["original_non_benign_values"] = (
        df.filter(pl.col("state").str.to_uppercase() != "BENIGN")["state"].unique().to_list()
    )

    df = df.with_columns(
        pl.col("state").map_elements(normalize_state, return_dtype=pl.Utf8).alias("_normalized")
    )

    if strategy["method"] == "rename" and expected is not None:
        df = df.with_columns(
            pl.when(pl.col("_normalized") == "BENIGN")
            .then(pl.lit("BENIGN")).otherwise(pl.lit(expected)).alias("state"),
            ((pl.col("_normalized") != "BENIGN") & (pl.col("_normalized") != expected)).alias("label_uncertain"),
        )
    else:
        df = df.with_columns(
            pl.col("_normalized").alias("state"),
            pl.lit(False).alias("label_uncertain"),
        )
    df = df.drop("_normalized")

    report["n_rows"] = len(df)
    report["n_uncertain_rows"] = int(df["label_uncertain"].sum())
    return df, report
